//! Friendly ZZZ name tables shared by tools/builds/edit-save.zig and tools/builds/inspect-save.zig:
//! the `Set` enum (set name → suit id), the `Avatar` enum (character name → avatar id),
//! the `Weapon` enum (W-Engine name → weapon id), and `propName` (property key →
//! readable name). Kept in one place so the writer (edit-save) and the reader
//! (inspect-save) can never disagree about a name.

const std = @import("std");

/// Gear-uid encoding bases. In the save, a gear item stores its raw uid `n`, but an
/// avatar's reference to it stores `n + base` (battle.zig subtracts the base to resolve
/// the reference back to the item). The two inventories use DIFFERENT bases, so both the
/// writer (edit-save) and the reader (inspect-save) import them from here to stay in lockstep:
/// - discs: an avatar slot stores `uid + equipment_uid_base` (Equipment.Uid.base in
///   gamesv/src/logic/Properties/Equipment.zig); the slot list is positional, 6 entries.
/// - W-Engines: an avatar's `weapon_uid` stores `uid + weapon_uid_base` (Weapon.Uid.base in
///   gamesv/src/logic/Properties/Weapon.zig); a single scalar, `0` = no weapon.
/// Get a base wrong and auto-equip silently references nothing.
pub const equipment_uid_base: u32 = 0x2_0000;
pub const weapon_uid_base: u32 = 0x1_0000;

/// Avatar (character) ids by their in-game names. Each character block in
/// tools/builds/builds.zon names one of these via `.avatar`, and edit-save auto-equips its
/// discs onto that avatar. Ids come from EnkaNetwork's ZZZ dataset (avatars.json
/// codename → locs.json "en" display name — same lineage as the `Set` ids). There is
/// no comptime cross-check table: avatar ownership is runtime state, and the repo's
/// AvatarBaseTemplateTb.zon dump predates these characters, so a wrong/unowned id is
/// caught at runtime (the character is reported and skipped). Add one line per new
/// character.
pub const Avatar = enum(u32) {
    // <gen:avatar> — generated by tools/builds/gen_names.py from EnkaNetwork data; do not edit by hand
    Anby = 1011, // Avatar_Female_Size02_Anbi
    Nekomata = 1021, // Avatar_Female_Size01_Tsubaki
    Nicole = 1031, // Avatar_Female_Size02_Nostradamus
    Soldier11 = 1041, // Avatar_Female_Size02_Longinus
    Yidhari = 1051, // Avatar_Female_Size03_Yidhari
    Corin = 1061, // Avatar_Female_Size01_Corin
    Caesar = 1071, // Avatar_Female_Size03_Caesar
    Billy = 1081, // Avatar_Male_Size03_Billy
    Miyabi = 1091, // Avatar_Female_Size02_Unagi
    Koleda = 1101, // Avatar_Female_Size01_OokumaMari
    Anton = 1111, // Avatar_Male_Size03_Anton
    Ben = 1121, // Avatar_Male_Size03_Ben
    Soukaku = 1131, // Avatar_Female_Size01_Aokaku
    Lycaon = 1141, // Avatar_Male_Size03_Lycaon
    Lucy = 1151, // Avatar_Female_Size01_Lucy
    Lighter = 1161, // Avatar_Male_Size02_Lighter
    Burnice = 1171, // Avatar_Female_Size02_Burnice
    Grace = 1181, // Avatar_Female_Size03_Lisa
    Ellen = 1191, // Avatar_Female_Size02_Ellen
    Harumasa = 1201, // Avatar_Male_Size01_Harumasa
    Rina = 1211, // Avatar_Female_Size03_Rina
    Yanagi = 1221, // Avatar_Female_Size03_Yanagi
    ZhuYuan = 1241, // Avatar_Female_Size03_ZhuYuan
    Qingyi = 1251, // Avatar_Female_Size01_QingYi
    Jane = 1261, // Avatar_Female_Size03_JaneDoe
    Seth = 1271, // Avatar_Male_Size01_Seth
    Piper = 1281, // Avatar_Female_Size01_Clara
    Hugo = 1291, // Avatar_Male_Size02_HugoVlad
    OrphieMagus = 1301, // Avatar_Female_Size02_Brujas
    AstraYao = 1311, // Avatar_Female_Size03_Astra
    Evelyn = 1321, // Avatar_Female_Size03_Evelyn
    Vivian = 1331, // Avatar_Female_Size02_Vivian
    Zhao = 1341, // Avatar_Female_Size00_XiaoZhao
    Pulchra = 1351, // Avatar_Female_Size03_Pulchra
    Trigger = 1361, // Avatar_Female_Size03_Trigger
    Yixuan = 1371, // Avatar_Female_Size03_YiXuan
    Soldier0Anby = 1381, // Avatar_Female_Size02_SilverAnby
    JuFufu = 1391, // Avatar_Female_Size01_Jufufu
    Alice = 1401, // Avatar_Female_Size02_Alice
    Yuzuha = 1411, // Avatar_Female_Size02_Yuzuha
    PanYinhu = 1421, // Avatar_Male_Size03_PanYinhu
    YeShunguang = 1431, // Avatar_Female_Size02_Zhenzhen
    Manato = 1441, // Avatar_Male_Size03_Norano
    Lucia = 1451, // Avatar_Female_Size02_Lucia
    Seed = 1461, // Avatar_Female_Size02_Seed
    Banyue = 1471, // Avatar_Male_Size03_BanYue
    Dialyn = 1481, // Avatar_Female_Size01_Azural
    Sunna = 1491, // Avatar_Female_Size01_Summer
    Aria = 1501, // Avatar_Female_Size01_Aria
    NangongYu = 1511, // Avatar_Female_Size01_NangongYu
    Cissia = 1521, // Avatar_Female_Size02_Cissia
    StarlightBilly = 1531, // Avatar_Male_Size03_SPBilly
    Promeia = 1541, // Avatar_Female_Size03_Promeia
    Pyrois = 1551, // Avatar_Male_Size03_Pyrois
    Velina = 1561, // Avatar_Female_Size03_Velina
    Norma = 1571, // Avatar_Female_Size01_Norma
    Remielle = 1581, // Avatar_Female_Size02_Remielle
    Sigrid = 1591, // Avatar_Female_Size03_Sigrid
    // </gen:avatar>
};

/// Equipment-set ids by their in-game names (sourced from EnkaNetwork's ZZZ
/// dataset; every 2-piece bonus was cross-checked against the bonuses in
/// EquipmentSuitTemplateTb.zon). Every disc in tools/builds/builds.zon names one of these
/// via `.set`. The two newest ids post-date the dataset snapshot and have no public
/// name yet, so they keep numeric placeholders.
pub const Set = enum(u32) {
    WoodpeckerElectro = 31000, // 2pc +8% CRIT Rate
    PufferElectro = 31100, // 2pc +8% PEN Ratio
    ShockstarDisco = 31200, // 2pc +6% Impact
    FreedomBlues = 31300, // 2pc +30 Anomaly Proficiency
    HormonePunk = 31400, // 2pc +10% ATK
    SoulRock = 31500, // 2pc +16% DEF
    SwingJazz = 31600, // 2pc +20% Energy Regen
    ChaosJazz = 31800, // 2pc +30 Anomaly Proficiency
    ProtoPunk = 31900, // 2pc special (no flat stat)
    InfernoMetal = 32200, // 2pc +10% Fire DMG
    ChaoticMetal = 32300, // 2pc +10% Ether DMG
    ThunderMetal = 32400, // 2pc +10% Electric DMG
    PolarMetal = 32500, // 2pc +10% Ice DMG
    FangedMetal = 32600, // 2pc +10% Physical DMG
    BranchBladeSong = 32700, // 2pc +16% CRIT DMG
    AstralVoice = 32800, // 2pc +10% ATK
    ShadowHarmony = 32900, // 2pc special (no flat stat)
    PhaethonsMelody = 33000, // 2pc +8% Anomaly Mastery
    YunkuiTales = 33100, // 2pc +10% HP
    KingOfTheSummit = 33200, // 2pc special (no flat stat)
    DawnsBloom = 33300, // 2pc special (no flat stat)
    MoonlightLullaby = 33400, // 2pc +20% Energy Regen
    WhiteWaterBallad = 33500, // 2pc +10% Physical DMG
    ShiningAria = 33600, // 2pc +10% Ether DMG
    BunnyInWonderland = 33700, // 2pc +10% HP
    NotesFromTheChained = 33800, // 2pc +10% Ice DMG
    WutheringSalon = 33900, // 2pc +10% Wind DMG
    TheSkyAblaze = 34000, // 2pc +10% Ether DMG
    FeatheredFate = 34100, // 2pc +10% ATK
    Set34200 = 34200, // 2pc +16% DEF (name not in dataset)
};

/// W-Engine (weapon) ids by their in-game names. Each character block in
/// tools/builds/builds.zon names one of these via `.weapon`, and edit-save adds one maxed
/// copy to the weapon inventory and auto-equips it onto that avatar. Ids are the
/// weapon `item_id` from EnkaNetwork's ZZZ dataset (weapons.json codename →
/// locs.json "en" display name — same lineage as the `Set`/`Avatar` ids); each is
/// cross-checked against WeaponTemplateTb.zon at comptime in edit-save (an id absent
/// from that table fails to compile). Add one line per new W-Engine.
pub const Weapon = enum(u32) {
    // <gen:weapon> — generated by tools/builds/gen_names.py from EnkaNetwork data; do not edit by hand
    LunarPleniluna = 12001, // Weapon_B_Common_01
    LunarDecrescent = 12002, // Weapon_B_Common_02
    LunarNoviluna = 12003, // Weapon_B_Common_03
    ReverbMarkI = 12004, // Weapon_B_Common_04
    ReverbMarkII = 12005, // Weapon_B_Common_05
    ReverbMarkIII = 12006, // Weapon_B_Common_06
    VortexRevolver = 12007, // Weapon_B_Common_07
    VortexArrow = 12008, // Weapon_B_Common_08
    VortexHatchet = 12009, // Weapon_B_Common_09
    MagneticStormAlpha = 12010, // Weapon_B_Common_10
    MagneticStormBravo = 12011, // Weapon_B_Common_11
    MagneticStormCharlie = 12012, // Weapon_B_Common_12
    IdentityBase = 12013, // Weapon_B_Common_13
    IdentityInflection = 12014, // Weapon_B_Common_14
    CinderCobalt = 12015, // Weapon_B_Common_15
    StreetSuperstar = 13001, // Weapon_A_Common_01
    SliceOfTime = 13002, // Weapon_A_Common_02
    RainforestGourmet = 13003, // Weapon_A_Common_03
    StarlightEngine = 13004, // Weapon_A_Common_04
    SteamOven = 13005, // Weapon_A_Common_05
    PreciousFossilizedCore = 13006, // Weapon_A_Common_06
    OriginalTransmorpher = 13007, // Weapon_A_Common_07
    WeepingGemini = 13008, // Weapon_A_Common_08
    ElectroLipGloss = 13009, // Weapon_A_Common_09
    BunnyBand = 13010, // Weapon_A_Common_10
    SpringEmbrace = 13011, // Weapon_A_Common_11
    PuzzleSphere = 13012, // Weapon_A_Common_12
    GildedBlossom = 13013, // Weapon_A_Common_13
    RadiowaveJourney = 13014, // Weapon_A_Common_14
    MarcatoDesire = 13015, // Weapon_A_Common_15
    ReelProjector = 13016, // Weapon_A_Common_16
    BoisterousEchoes = 13018, // Weapon_A_Common_18
    CauldronOfClarity = 13019, // Weapon_A_Common_19
    TheSimmeringPot = 13020, // Weapon_A_Common_20
    DemaraBatteryMarkII = 13101, // Weapon_A_1011
    TheVault = 13103, // Weapon_A_1031
    Housekeeper = 13106, // Weapon_A_1061
    StarlightEngineReplica = 13108, // Weapon_A_1081
    DrillRigRedAxis = 13111, // Weapon_A_1111
    BigCylinder = 13112, // Weapon_A_1121
    BashfulDemon = 13113, // Weapon_A_1131
    KaboomTheCannon = 13115, // Weapon_A_1151
    PeacekeeperSpecialized = 13127, // Weapon_A_1271
    RoaringRide = 13128, // Weapon_A_1281
    BoxCutter = 13135, // Weapon_A_1351
    TremorTrigramVessel = 13142, // Weapon_A_1421
    GrillOWisp = 13144, // Weapon_A_1441
    CannonRotor = 14001, // Weapon_S_Common_01
    UnfetteredGameBall = 14002, // Weapon_S_Common_02
    SixShooter = 14003, // Weapon_S_Common_03
    SteelCushion = 14102, // Weapon_S_1021 (Nekomata)
    TheBrimstone = 14104, // Weapon_S_1041 (Soldier 11)
    KrakenSCradle = 14105, // Weapon_S_1051 (Yidhari)
    TusksOfFury = 14107, // Weapon_S_1071 (Caesar)
    HailstormShrine = 14109, // Weapon_S_1091 (Miyabi)
    HellfireGears = 14110, // Weapon_S_1101 (Koleda)
    TheRestrained = 14114, // Weapon_S_1141 (Lycaon)
    BlazingLaurel = 14116, // Weapon_S_1161 (Lighter)
    FlamemakerShaker = 14117, // Weapon_S_1171 (Burnice)
    FusionCompiler = 14118, // Weapon_S_1181 (Grace)
    DeepSeaVisitor = 14119, // Weapon_S_1191 (Ellen)
    ZanshinHerbCase = 14120, // Weapon_S_1201 (Harumasa)
    WeepingCradle = 14121, // Weapon_S_1211 (Rina)
    Timeweaver = 14122, // Weapon_S_1221 (Yanagi)
    RiotSuppressorMarkVI = 14124, // Weapon_S_1241 (Zhu Yuan)
    IceJadeTeapot = 14125, // Weapon_S_1251 (Qingyi)
    SharpenedStinger = 14126, // Weapon_S_1261 (Jane)
    MyriadEclipse = 14129, // Weapon_S_1291 (Hugo)
    BellicoseBlaze = 14130, // Weapon_S_1301 (Orphie & Magus)
    ElegantVanity = 14131, // Weapon_S_1311 (Astra Yao)
    HeartstringNocturne = 14132, // Weapon_S_1321 (Evelyn)
    FlightOfFancy = 14133, // Weapon_S_1331 (Vivian)
    HalfSugarBunny = 14134, // Weapon_S_1341 (Zhao)
    SpectralGaze = 14136, // Weapon_S_1361 (Trigger)
    QingmingBirdcage = 14137, // Weapon_S_1371 (Yixuan)
    SeveredInnocence = 14138, // Weapon_S_1381 (Soldier 0 - Anby)
    RoaringFurNace = 14139, // Weapon_S_1391 (Ju Fufu)
    PracticedPerfection = 14140, // Weapon_S_1401 (Alice)
    Metanukimorphosis = 14141, // Weapon_S_1411 (Yuzuha)
    CloudcleaveRadiance = 14143, // Weapon_S_1431 (Ye Shunguang)
    DreamlitHearth = 14145, // Weapon_S_1451 (Lucia)
    CordisGermina = 14146, // Weapon_S_1461 (Seed)
    WrathfulVajra = 14147, // Weapon_S_1471 (Banyue)
    YesterdayCalls = 14148, // Weapon_S_1481 (Dialyn)
    Thoughtbop = 14149, // Weapon_S_1491 (Sunna)
    AngelInTheShell = 14150, // Weapon_S_1501 (Aria)
    NeonFantasies = 14151, // Weapon_S_1511 (Nangong Yu)
    SerpentineSeeker = 14152, // Weapon_S_1521 (Cissia)
    StarlightRiderFaceplate = 14153, // Weapon_S_1531 (Starlight - Billy)
    FrostfallSickle = 14154, // Weapon_S_1541 (Promeia)
    SolExuvia = 14155, // Weapon_S_Common_04
    JoyauDore = 14156, // Weapon_S_1561 (Velina)
    ChiefSidekick = 14157, // Weapon_S_1571 (Norma)
    PoemOfTheEmptyFeatherReturn = 14158, // Weapon_S_1581 (Remielle)
    SigridSignature = 14159, // Weapon_S_1591 (Sigrid; name not in dataset)
    // </gen:weapon>
};

/// Reverse lookup: suit id → friendly `Set` name, or null if unknown.
pub fn setName(id: u32) ?[]const u8 {
    inline for (@typeInfo(Set).@"enum".fields) |f|
        if (f.value == id) return f.name;
    return null;
}

/// Reverse lookup: weapon id → friendly `Weapon` name, or null if unknown.
pub fn weaponName(id: u32) ?[]const u8 {
    inline for (@typeInfo(Weapon).@"enum".fields) |f|
        if (f.value == id) return f.name;
    return null;
}

/// Reverse lookup: avatar id → friendly `Avatar` name, or null if unknown.
pub fn avatarName(id: u32) ?[]const u8 {
    inline for (@typeInfo(Avatar).@"enum".fields) |f|
        if (f.value == id) return f.name;
    return null;
}

/// Friendly name for a property key (display only).
pub fn propName(key: u32) []const u8 {
    return switch (key) {
        11103 => "HpFlat",
        11102 => "HpPct",
        12103 => "AtkFlat",
        12102 => "AtkPct",
        12202 => "Impact",
        13103 => "DefFlat",
        13102 => "DefPct",
        20103 => "CritRate",
        21103 => "CritDmg",
        23203 => "PenFlat",
        23103 => "PenRatio",
        30502 => "EnergyRegen",
        31203 => "AnomProf",
        31402 => "AnomMastery",
        31503 => "PhysDmg",
        31603 => "FireDmg",
        31703 => "IceDmg",
        31803 => "ElecDmg",
        31903 => "EtherDmg",
        32303 => "WindDmg",
        else => "?",
    };
}
